### ISSUE TITLE
How to get more tests?

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-test-runner#1]
Setting up the test runner gives me 20 tests for citations, all pretty basic with no locators or so. How can I get more tests, like for the bibliography or for testing the position logic?

**Comment by denismaier** [comment]
Ok. Browsing through the citeproc-js repo I've realized that explanations actually do exist, [here](https://github.com/citation-style-language/test-suite/blob/10f19d651202290d163662573f5897f768b51c4a/README.rst). Perhaps they should be linked in the readme?

**Comment by fbennett** [comment]
Good point. I've added a note to the README, and pulled in some changes I've been using locally.
