### ISSUE TITLE
Add `citation-all` as mode

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-test-runner#11]
For styles that don’t print a bibliography, it would be great to have a `citation-all` mode which tests for all citation variants like the `all` mode but leaves out the `bibliography` section.

**Comment by fbennett** [comment]
Couldn't that just be made implicit?

**Comment by georgd** [comment]
> Couldn't that just be made implicit?

That would be even better. Currently, it’s throwing an error with mode `all` when the bibliography section is absent. I just started looking through the libs and found out that there’s `styleCapabilities` with a key `bibliography` — looks like you already foresaw this? :)

**Comment by fbennett** [comment]
Seems not to be throwing an error now, closing.

**Comment by georgd** [comment]
It doesn’t fail because I included a `bibliography` section with a `<text value=""/> inside `cs:layout`. Without that, it still did, when I tested last time.

**Comment by georgd** [comment]
Ok, it indeed doesn’t throw an error any longer. Just tested with a modified style.
