### ISSUE TITLE
CTR doesn’t process accessed variable

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-test-runner#14]
[This works fine with Juris-M but not with citeproc-test-runner]

Using jm-ibfd, tests like https://github.com/georgd/jm-style-tests/blob/jm-ibfd/jm-ibfd-with-page-label/countreyKeyFeatures_test021.txt fail. I suspected the date format of `accessed` was the culprit but trying all that I know of didn’t help. 

`cslrun -U` produces something like `"accessed": "2014-12-09",`. I tried changing this to `raw`, `literal` and `date-parts`.

Edit: this isn’t new. It never worked for me since I started to use CTR.

**Comment by fbennett** [comment]
There is a missing ``c`` in ``accessed``. :-)

**Comment by georgd** [comment]
OMG, two typos in one night :D

So, with proper date formatting it works. Should I open a new ticket for `cslrun -U` producing `"accessed": "2014-12-09"`?

**Comment by fbennett** [comment]
Here I'm getting this with the ``-U`` option:
```
    "accessed": {
      "date-parts": [
        [
          2002,
          1,
          1
        ]
      ]
    },
```

**Comment by georgd** [comment]
Maybe some issues with localised dates in Juris-M? I have observed that with other fields too but can’t currently remember what I have to enter to make it work correctly.

**Comment by fbennett** [comment]
The test runner code base is separate from Juris-M, and pulls data from the zotero.org API. I could well be missing sometime, but it looks as though if there is some difference in input that triggers the invalid output, it would have to originate in zotero.org.

What does ``cslrun --version`` report? (If the option throws an error, it's an older version.)

**Comment by georgd** [comment]
`cslrun --version` reports `1.1.110`.

With `cslrun -U`, the item at https://api.zotero.org/groups/2352960/items/G658GSQU is showing

- `accessed` as ` "accessed": "2020-08-04"`
- `issued` as 
```json
    "issued": {
      "raw": "2019-12-20"
    },
``` 

Both dates are entered in ISO format.

**Comment by fbennett** [comment]
Finally reproduced it. The code that performs conversion depends on an early Zotero->CSL converter, with extra stuff added to handle CSL-M items. I've applied a fix that should help with dates generally.

Zotero and Jurism now have a nice mapping table to support conversions, which makes things much simpler. At some point I should rewrite the API conversion module to use that instead of this tangled bundle of old stuff.

**Comment by fbennett** [comment]
Oh -- into the bargin, I added paging support to the ``-U`` option. You may get some additional tests, depending on how many items are in your test library.

**Comment by georgd** [comment]
The example given above in https://github.com/Juris-M/citeproc-test-runner/issues/14#issuecomment-713145420 hasn’t changed after updating the CTR (via npm).

**Comment by fbennett** [comment]
Version 1.1.111 of ``citeproc-test-runner`` produces the output below with ``cslrun -w ../path/to/styles/jm-indigobook-law-review.csl -U``. It writes the ``raw`` form, but the processor seems to handle that okay. Is that what you see in your results as well? I can make it output the array form when I have time to refactor and simplify the conversion function.

```
>>===== INPUT =====>>
[
  {
    "type": "post-weblog",
    "title": "Justin Bieber Fronts V Magazine's Music Issue (Forum Buzz)",
    "author": [
      {
        "given": "Chrissy",
        "family": "Makkas"
      }
    ],
    "container-title": "The Fashion Spot",
    "issued": {
      "raw": "2012-01-11"
    },
    "URL": "https://www.thefashionspot.com/buzz-news/forum-buzz/171203-justin-bieber-fronts-v-magazines-music-issue-forum-buzz/",
    "accessed": {
      "raw": "2020-02-22"
    },
    "multi": {
      "main": {},
      "_keys": {}
    }
  }
]
<<===== INPUT =====<<
```

**Comment by georgd** [comment]
After a second `cslrun -U`, it’s the `raw` date in `accessed` too and indeed, it works, the tests are passing. So, no need to change that from my side :) Thank you!

**Comment by fbennett** [comment]
Excellent news. I'm really excited about your work on Austrian styles, and about Samuel's work on Canada. It's been a long, long road feeling out the requirements, and it's great to see the tool taken up and put to use.
