### ISSUE TITLE
Renaming conventions for tests?

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-test-runner#2]
How should the tests be named? Any rules for that? Or at least best practices? Will the test runner simply use every text file found in the subdirectory as input?

**Comment by fbennett** [comment]
The runner now names tests with a template "style_test999.txt," where "999" is a unique zero-padded number, assigned in sequence after filling any gaps in the series. There is a DESCRIPTION section in the test templates now, which shows up in mocha error reports, and you can edit the content. With the test description, the names of the tests are less of an issue, although it might be convenient to group them (i.e. change the part of the name before the underscore).
