### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-test-runner#3]
Would it be possible to add a simple validation option? 

Also, a possibility to ignore validation errors in test runs would also be great.

**Comment by fbennett** [comment]
Should be able to do both, I'll look when I get a chance. It would also be good to disable watching with the -w option, so that you can just check and exit.

**Comment by fbennett** [comment]
Try updating and see how it goes. There are two new options, -O (once) and -N (no-validation), and the -c (cranky/validate-only) option works with -w now. `cslrun -h` throws up an option listing.

**Comment by denismaier** [comment]
Thanks. -O -N and -c are really useful.

**Comment by fbennett** [comment]
We now have -V|--validate in the mix as well, to validate style modules. Details from ``cslrun --help``.
